[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = [
  "npm ci",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npm run build",
  "npx prisma migrate deploy || true"
]

[start]
cmd = "npm run start:next"
